version: "3.7"
services:

  zeebe:
    build:
      context: zeebe/
      dockerfile: Dockerfile
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    tmpfs:
      - /usr/local/zeebe/data
    logging:
      driver: 'none'

  monitor:
    image: camunda/zeebe-simple-monitor:0.20.0
    env_file:
      - "${PWD}/env/zeebe_monitor.env"
    ports:
      - 8082:8082
    logging:
      driver: 'none'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    tmpfs: '/usr/share/elasticsearch/data'
    logging:
      driver: 'none'

  operate:
    image: camunda/operate:0.26.0
    env_file:
      - "${PWD}/env/zeebe_operate.env"
    ports:
      - 8087:8080
#    logging:
#      driver: 'none'

#  zeebe-http-worker:
#    image: camunda/zeebe-http-worker:latest
#    environment:
#      ZEEBE_CLIENT_BROKER_CONTACTPOINT: 'zeebe:26500'
##    logging:
##      driver: "none"
