version: "3.7"
services:

  zeebe:
    build:
      context: zeebe/
      dockerfile: Dockerfile
    ports:
      - "26500:26500"
      - "5701:5701"
    tmpfs: 
      - /usr/local/zeebe/data

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.19.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
